[package]
name = "tolla_proto"
version = "0.1.0"
authors = ["hoffa2 <helhof@online.no>"]

[dependencies]
prost = "0.2.0"
bytes = "0.4"
prost-derive = "0.2.0"
tokio-proto = "0.1.1"
tokio-io = "0.1"

[build-dependencies]
prost-build = "0.1.0"
